# Generated by Django 5.0 on 2024-01-01 11:55

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meta_title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clients')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='news')),
                ('summary', models.TextField()),
                ('content', tinymce.models.HTMLField()),
            ],
            options={'verbose_name_plural': 'Newses', 'ordering': ('-date',)},
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='projects')),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
            options={'verbose_name_plural': 'Portfolios', 'ordering': ('-date',)},
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('HOME_AUTOMATION', 'Home & Office Automation'),
                            ('SECURITY_SURVEILLANCE', 'Security & Surveillance'),
                        ],
                        max_length=50,
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
            options={'ordering': ('order',)},
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topline', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='sliders')),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'media',
                    models.CharField(
                        choices=[
                            ('fab fa-facebook-f', 'facebook'),
                            ('fab fa-twitter', 'twitter'),
                            ('fab fa-behance', 'behance'),
                            ('fab fa-pinterest-p', 'pinterest'),
                            ('fab fa-instagram', 'instagram'),
                            ('fab fa-dribbble', 'dribbble'),
                            ('fab fa-linkedin-in', 'linkedin'),
                            ('fab fa-youtube', 'youtube'),
                            ('fab fa-vimeo-v', 'vimeo'),
                            ('fab fa-google-plus-g', 'google'),
                            ('fab fa-skype', 'skype'),
                            ('fab fa-tumblr', 'tumblr'),
                            ('fab fa-github', 'github'),
                        ],
                        max_length=100,
                    ),
                ),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'verbose_name_plural': 'Vacancies', 'ordering': ('-date',)},
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.service'
            ),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='job_applications')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.vacancy')),
            ],
        ),
    ]
