# Generated by Django 5.0 on 2024-01-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0002_portfolio_category_remove_portfolio_service_and_more')]

    operations = [
        migrations.AlterField(model_name='portfolio_category', name='category', field=models.CharField(max_length=50))
    ]
