# Generated by Django 5.0 on 2024-01-01 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('web', '0003_alter_portfolio_category_category')]

    operations = [
        migrations.RenameField(model_name='portfolio', old_name='Portfolio_Category', new_name='portfolio_category')
    ]
