# Generated by Django 5.0 on 2024-01-01 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('web', '0004_rename_portfolio_category_portfolio_portfolio_category')]

    operations = [migrations.RenameModel(old_name='Portfolio_Category', new_name='PortfolioCategory')]
