# Generated by Django 5.0 on 2024-01-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0005_rename_portfolio_category_portfoliocategory')]

    operations = [
        migrations.CreateModel(
            name='Testimonail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
            ],
        )
    ]
