# Generated by Django 5.0 on 2024-01-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0007_enquiry')]

    operations = [migrations.AlterField(model_name='enquiry', name='contact', field=models.IntegerField())]
