# Generated by Django 5.0 on 2024-01-02 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0008_alter_enquiry_contact')]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='service_image'),
            preserve_default=False,
        )
    ]
