# Generated by Django 5.0 on 2024-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0009_service_image')]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_image'),
        )
    ]
